#!/usr/bin/env bats
# Tests for scripts/check-upgrade-has-changes.sh — Issue #90.
#
# PR #89 raised a "dependency upgrade" PR even though no Cargo.toml manifest
# was actually advanced — only Cargo.lock drifted (transitive bump of
# hashbrown 0.17.0 -> 0.17.1). `cargo upgrade` touches the lockfile to
# refresh transitive deps even when every available bump is blocked by
# semver, so a Cargo.lock-only diff is not a meaningful upgrade and should
# not trigger a PR. The script under test makes that distinction explicit:
# it reports `changed=true` only when at least one Cargo.toml has changed.

setup() {
  SCRIPT_UNDER_TEST="${BATS_TEST_DIRNAME}/../../scripts/check-upgrade-has-changes.sh"
  [ -x "$SCRIPT_UNDER_TEST" ] || chmod +x "$SCRIPT_UNDER_TEST"

  TMP_REPO="$(mktemp -d)"
  export TMP_REPO

  # Build a minimal Cargo workspace and commit the baseline so every test
  # case can diff against HEAD deterministically.
  git -C "$TMP_REPO" init -q -b main
  git -C "$TMP_REPO" config user.email "test@example.com"
  git -C "$TMP_REPO" config user.name "Test"
  mkdir -p "$TMP_REPO/rust_scorer"
  cat >"$TMP_REPO/Cargo.toml" <<'EOF'
[workspace]
members = ["rust_scorer"]
resolver = "2"
EOF
  cat >"$TMP_REPO/rust_scorer/Cargo.toml" <<'EOF'
[package]
name = "rust_scorer"
version = "0.5.25"
edition = "2021"

[dependencies]
serde = "1.0.210"
EOF
  cat >"$TMP_REPO/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "serde"
version = "1.0.210"
EOF
  git -C "$TMP_REPO" add .
  git -C "$TMP_REPO" commit -q -m "baseline"
}

teardown() {
  rm -rf "$TMP_REPO"
}

@test "reports changed=false when nothing changed" {
  run "$SCRIPT_UNDER_TEST" --repo "$TMP_REPO"
  [ "$status" -eq 0 ]
  [[ "$output" == *"changed=false"* ]]
}

@test "reports changed=false when only Cargo.lock changed (Issue #90)" {
  # Simulate the exact pattern from PR #89: a transitive bump in Cargo.lock
  # with no manifest change. This is the failure case the issue calls out.
  cat >"$TMP_REPO/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "serde"
version = "1.0.210"

[[package]]
name = "hashbrown"
version = "0.17.1"
EOF
  run "$SCRIPT_UNDER_TEST" --repo "$TMP_REPO"
  [ "$status" -eq 0 ]
  [[ "$output" == *"changed=false"* ]]
}

@test "reports changed=true when a workspace-member Cargo.toml changed" {
  sed -i.bak 's/serde = "1.0.210"/serde = "1.0.211"/' \
    "$TMP_REPO/rust_scorer/Cargo.toml"
  rm -f "$TMP_REPO/rust_scorer/Cargo.toml.bak"
  run "$SCRIPT_UNDER_TEST" --repo "$TMP_REPO"
  [ "$status" -eq 0 ]
  [[ "$output" == *"changed=true"* ]]
}

@test "reports changed=true when the root Cargo.toml changed" {
  cat >>"$TMP_REPO/Cargo.toml" <<'EOF'

[workspace.dependencies]
clap = "4.5.21"
EOF
  run "$SCRIPT_UNDER_TEST" --repo "$TMP_REPO"
  [ "$status" -eq 0 ]
  [[ "$output" == *"changed=true"* ]]
}

@test "reports changed=true when both Cargo.toml and Cargo.lock changed" {
  sed -i.bak 's/serde = "1.0.210"/serde = "1.0.211"/' \
    "$TMP_REPO/rust_scorer/Cargo.toml"
  rm -f "$TMP_REPO/rust_scorer/Cargo.toml.bak"
  printf '\n[[package]]\nname = "extra"\nversion = "1.0.0"\n' \
    >>"$TMP_REPO/Cargo.lock"
  run "$SCRIPT_UNDER_TEST" --repo "$TMP_REPO"
  [ "$status" -eq 0 ]
  [[ "$output" == *"changed=true"* ]]
}

@test "rejects unknown options with usage error" {
  run "$SCRIPT_UNDER_TEST" --bogus
  [ "$status" -eq 2 ]
  [[ "$output" == *"unknown option"* ]]
}

@test "--help prints usage and exits 0" {
  run "$SCRIPT_UNDER_TEST" --help
  [ "$status" -eq 0 ]
  [[ "$output" == *"Usage: check-upgrade-has-changes.sh"* ]]
}

@test "errors clearly when --repo is not a git repository" {
  local not_a_repo
  not_a_repo="$(mktemp -d)"
  run "$SCRIPT_UNDER_TEST" --repo "$not_a_repo"
  [ "$status" -ne 0 ]
  [[ "$output" == *"not a git repository"* ]]
  rm -rf "$not_a_repo"
}

@test "upgrade-dependencies workflow uses the script and drops Cargo.lock from the trigger check" {
  local wf="${BATS_TEST_DIRNAME}/../../.github/workflows/upgrade-dependencies.yml"
  [ -f "$wf" ]
  run grep -F "scripts/check-upgrade-has-changes.sh" "$wf"
  [ "$status" -eq 0 ]
  # The old logic checked Cargo.lock alongside Cargo.toml; the new logic
  # must rely on the script, which deliberately ignores Cargo.lock.
  run grep -F "git diff --quiet -- 'Cargo.toml' '**/Cargo.toml' 'Cargo.lock'" "$wf"
  [ "$status" -ne 0 ]
}
